import { Geist, Geist_Mono } from "next/font/google";
import AppProviders from "@/components/AppProviders";
import BoneCursorEffects from "@/components/BoneCursorEffects";
import Footer from "@/components/Footer";
import Header from "@/layout/Header";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <AppProviders>
            <BoneCursorEffects />
            <Header />
            <div className="flex-1">{children}</div>
            <Footer />
          </AppProviders>
        </AuthProvider>
      </body>
    </html>
  );
}
